import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// Old WordPress addresses -> new pages, so Google rankings and old links carry over.
const old = {
  '/iv-infusion-menu': '/iv-therapy/',
  '/ithrive-a-la-carte-menu': '/iv-therapy/',
  '/ingredient-list': '/iv-therapy/#ingredients',
  '/why-iv-hydration-ithrive': '/iv-therapy/',
  '/our-services': '/',
  '/iempower': '/iv-therapy/#iempower',
  '/iprotect': '/iv-therapy/#iprotect',
  '/ialleviate': '/iv-therapy/#ialleviate',
  '/irecover': '/iv-therapy/#irecover',
  '/iglow': '/iv-therapy/#iglow',
  '/itrim-ienergize': '/iv-therapy/#itrim',
  '/icleanse': '/iv-therapy/#icleanse',
  '/iforeveryoung': '/iv-therapy/#iforeveryoung',
  '/ithrive-iv-infusions': '/iv-therapy/#ithrive',
  '/izen': '/iv-therapy/',
  '/iintimate': '/iv-therapy/',
  '/nad': '/iv-therapy/#nad',
  '/vitamin-c': '/iv-therapy/#vitamin-c',
  '/glutathione': '/injections/',
  '/vitamin-b12': '/injections/',
  '/b-complex-shot': '/injections/',
  '/biotin-injections': '/injections/',
  '/magnesium': '/injections/',
  '/zinc': '/injections/',
  '/vitamin-d3': '/injections/',
  '/amino-blend-shot': '/injections/',
  '/arginine-shot': '/injections/',
  '/carnitine-shot': '/injections/',
  '/coq10-shot': '/injections/',
  '/lipotropic': '/injections/',
  '/immunizer': '/injections/',
  '/immunizer-signature-shot': '/injections/',
  '/head-reliever': '/injections/',
  '/head-reliever-signature-shot': '/injections/',
  '/famotidine-pepcid': '/iv-therapy/',
  '/reglan': '/iv-therapy/',
  '/toradol': '/iv-therapy/',
  '/zofran-anti-nausea': '/iv-therapy/',
  '/benadryl-anti-histamine': '/iv-therapy/',
  '/semaglutide': '/weight-loss/#medications',
  '/tirzepatide': '/weight-loss/#medications',
  '/oral-medication': '/weight-loss/#medications',
  '/itrim-metabolic-weight-loss': '/weight-loss/#support',
  '/iv-injections-micc-lipotropic-injections': '/weight-loss/#support',
  '/hormone-replacement-therapy': '/hormone-therapy/',
  '/membership-plans': '/membership/',
  '/about-us': '/about/',
  '/meet-the-crew-team': '/about/#team',
  '/ruth-nyang-fnp-c': '/about/#ruth',
  '/mankah-tadfor': '/about/#team',
  '/laiven-jean-de-chantal-rn': '/about/#team',
  '/contact-us': '/contact/',
};

export default defineConfig({
  site: 'https://ithriveinfusion.com',
  trailingSlash: 'always',
  redirects: old,
  integrations: [sitemap()],
});
